/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jashburn.gradle.java_app_with_lib.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
